import React from 'react'
import Footer from '../../components/footer/Footer'
import MetaData from '../../components/MetaData'
import './style.css'

const HelpPage = () => {
  return (
    <>
    <MetaData title='Help'/>
    <main>
    <div className='help-container'>
      <h3 className='help-welcome'>Welcome to our Help page! We're here to assist you with any questions or issues you may have.</h3>
      <h2>Frequently Asked Questions</h2>
      <p>Here are some common questions and answers that might address your concerns:</p>
      <ul>
        <li>
          <h3>How do I download past question papers?</h3>
          <p>To download past question papers, navigate to the respective course and click on the download button provided next to each paper. The papers are available in PDF format for easy access and offline use.</p>
        </li>
        <li>
          <h3>Are the answers generated by GPT accurate?</h3>
          <p>Yes, the answers generated by GPT are carefully designed to provide accurate and reliable information. However, please note that these answers are generated by an AI model and may not always be perfect. We recommend cross-referencing the answers with your course material and consulting with your instructors for any doubts or clarifications.</p>
        </li>
        <li>
          <h3>How can I contribute to the articles section?</h3>
          <p>We welcome contributions from the community! If you have a topic of interest or expertise, you can submit your article idea to our editorial team. They will review the submissions and get in touch with you regarding the publishing process.</p>
        </li>
      </ul>
      <h2>Contact Us</h2>
      <p>If you have any further questions or need assistance, please feel free to reach out to our support team:</p>
      <ul>
        <li>Email: support@yourwebsite.com</li>
        <li>Phone: +1234567890</li>

      </ul>
      <p>Our support team is available during business hours and will respond to your inquiries as soon as possible.</p>
    </div>
    <Footer/>
    </main>
    
    </>
  
  )
}

export default HelpPage


